.TH OSCR 1
.SH NAME
oscr \-
local router for Open Sound Control (\s-1OSC\s0)
.
.SH SYNOPSIS
.B oscr
.RB [ \-uth ]
.RB [ \-U
.IR socket ]
.RB [ \-p
.IR port ]
.RB [ \-o
.IR proto ]
.I config
.br
.B oscr
.RB [ \-uth ]
.RB [ \-U
.IR socket ]
.RB [ \-p
.IR port ]
.RB [ \-o
.IR proto ]
<
.I config
.
.SH DESCRIPTION
.B oscr
is a simple local router for Open Sound Control (\s-1OSC\s0).
It allows multiple hosts on the same machine to receive messages from
.SM OSC
clients via a unified port.
.PP
.B oscr
reads routing information from a config file.
The syntax of the config file is very simple:
.PP
.in +4n
.EX
# comments
path -> port
# or alternatively
port <- path
.EE
.in
.PP
.
You can find an exmaple config file in the
.B EXAMPLE CONIGS
section.
.PP
After setting up a config file, you can start the router on port
.B 10000
with the default \s-1UDP\s0 protocol by executing
.PP
.in +4n
.EX
$ \fBoscr\fP -p10000 config
.EE
.in
.PP
or alternatively with \s-1TCP\s0 protocol by
.PP
.in +4n
.EX
$ \fBoscr\fP -t -p10000 config
.EE
.in
.PP
You can also use \s-1UNIX\s0 domain sockets with the
.B -U
option
.PP
.in +4n
.EX
$ \fBoscr\fP -U/tmp/osc.sock config
.EE
.in
.PP
After the router is running, any messages sent to the designated port or socket
(in this case
.B 10000
or
.BR /tmp/osc.sock )
will be dispatched to corresponding hosts specified in the config.
.SH OPTIONS
.TP
.B \-h
Print usage and exit.
.TP
.B \-u
Start
.SM OSC
server in
.SM UDP
mode.
.SM UDP
is used by default even if this option is not specified.
.TP
.B \-t
Start
.SM OSC
server in
.SM TCP
mode.
.TP
.BI \-U " socket"
Start server in \s-1UNIX\s0 domain socket mode.
.I socket
specifies the listening socket.
.TP
.BI \-p " port"
Specify the listening port number for \s-1UDP\s0 or \s-1TCP\s0 protocol.
It can also be a service name in
.BR /etc/services .
If not set, an unused port will be chosen by the system.
.
This option is ignored if
.B \-U
flag is set.
.TP
.BI \-o " proto"
Set the protocol for outgoing messages. The option
.I proto
must be one of
.B u
for \s-1UDP\s0,
.B t
for \s-1TCP\s0, and
.B U
for \s-1UNIX\s0 domain socket. The default for
.I proto
is
.B u
for \s-1UDP\s0 and \s-1TCP\s0 mode, and
.B U
for \s-1UNIX\s0 domain socket mode.
.
.SH EXAMPLE CONFIGS
The config file below routes messages from
.B /1/push1
to
.B localhost:10001
and messages from
.B /1/push2
to
.BR localhost:10002 .
.PP
.in +4n
.EX
# example config
/1/push1 -> 10001
/1/push2 -> 10002
.EE
.in
.PP
You can alternatively reverse the arrows:
.PP
.in +4n
.EX
# example config
10001 <- /1/push1
10002 <- /1/push2
.EE
.in
.PP
The two examples above behave exactly the same.
.PP
For \s-1UNIX\s0 domain sockets, use socket paths instead of port numbers:
.PP
.in +4n
.EX
# example config for UNIX domain socket
/1/push1 -> /tmp/1.sock
/1/push2 -> /tmp/2.sock
.EE
.in
.PP
